spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/api/users/**, /api/cards/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: ${ORDER_SERVICE_URI}
          predicates:
            - Path=/api/orders/**, /api/items/**, /api/order-items/**
          filters:
            - StripPrefix=1
